/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import entity.Account;
import entity.Employee;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author khanh
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }
    private Account account;

    public MainForm(Account account) {
        initComponents();
        this.account = account;
        if (account.getRole().getRole().equals("giáo vụ")) {
            btnEmpManager.setEnabled(false);
            btnStuManager.setEnabled(false);
        } else if (account.getRole().getRole().equals("ctsv")) {
            btnClassManager.setEnabled(false);
            btnSubManager.setEnabled(false);
            btnEmpManager.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEmpManager = new javax.swing.JButton();
        btnStuManager = new javax.swing.JButton();
        btnClassManager = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSubManager = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuDetailAcc = new javax.swing.JMenuItem();
        jMenuRePass = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main form");
        setMinimumSize(new java.awt.Dimension(419, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("STUDENT MS");

        btnEmpManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEmpManager.setText("Quản lý nhân viên");
        btnEmpManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpManagerActionPerformed(evt);
            }
        });

        btnStuManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStuManager.setText("Quản lý sinh viên");
        btnStuManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuManagerActionPerformed(evt);
            }
        });

        btnClassManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClassManager.setText("Quản lý lớp học");
        btnClassManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassManagerActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSubManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubManager.setText("Quản lý môn học");
        btnSubManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubManagerActionPerformed(evt);
            }
        });

        jMenu2.setText("Tài khoản");

        jMenuDetailAcc.setText("Thông tin tài khoản");
        jMenuDetailAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDetailAccActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuDetailAcc);

        jMenuRePass.setText("Thay đổi mật khẩu");
        jMenuRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRePassActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRePass);

        jMenuLogout.setText("Đăng xuất");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuLogout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStuManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClassManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubManager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnEmpManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnStuManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnClassManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSubManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát khỏi chương trình", "Message", JOptionPane.WARNING_MESSAGE);
        if (choose == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEmpManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpManagerActionPerformed
        // TODO add your handling code here:
        EmployeeManagerForm emp = new EmployeeManagerForm(account);
        emp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpManagerActionPerformed

    private void btnSubManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubManagerActionPerformed
        // TODO add your handling code here:
        SubjectManagerForm subjectManagerForm = new SubjectManagerForm(account);
        subjectManagerForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSubManagerActionPerformed

    private void btnClassManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassManagerActionPerformed
        // TODO add your handling code here:
        ClassManagerForm classManagerForm = new ClassManagerForm(account);
        classManagerForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClassManagerActionPerformed

    private void btnStuManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuManagerActionPerformed
        // TODO add your handling code here:
        StudentManagerForm studentManagerForm = new StudentManagerForm(account);
        studentManagerForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStuManagerActionPerformed

    private void jMenuDetailAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDetailAccActionPerformed
        try {
            // TODO add your handling code here:
            Employee e = Employee.getEmployee(account.getId());
            EmployeeForm employeeForm = new EmployeeForm(e);
            employeeForm.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thực hiện truy vấn. Vui lòng kiểm tra lại", "Message", JOptionPane.WARNING_MESSAGE);
            System.err.println(ex.getMessage());
        }

    }//GEN-LAST:event_jMenuDetailAccActionPerformed

    private void jMenuRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRePassActionPerformed
        // TODO add your handling code here:
        ResetPassForm resetPassForm = new ResetPassForm(account);
        resetPassForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuRePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassManager;
    private javax.swing.JButton btnEmpManager;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStuManager;
    private javax.swing.JButton btnSubManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDetailAcc;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuRePass;
    // End of variables declaration//GEN-END:variables
}
