/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import entity.Account;
import entity.ClassObj;
import entity.Schedule;
import entity.Subject;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author khanh
 */
public class ScheduleForm extends javax.swing.JFrame {

    /**
     * Creates new form ScheduleForm
     */
    public ScheduleForm() {
        initComponents();
    }
    private Account account;
    private ClassObj c;
    private Schedule s;

    public ScheduleForm(Account acc, ClassObj c, Schedule s) {
        initComponents();
        this.account = acc;
        this.c = c;
        this.s = s;
        try {
            loadCombobox();
            if (s != null) {
                cbxSubject.setSelectedItem(Subject.getSubjectByName(s.getSubject().getSubjectName()));
                txtTeacher.setText(s.getTeacher());
                cbxTeachingFrameTime.setSelectedItem(s.getTeachingFrameTime());
                txtTeachingTime.setText("" + s.getTeachingTime());
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date startDate = sdf.parse(s.getStartDate());
                Date endDate = sdf.parse(s.getEndDate());
                jStartDateChooser.setDate(startDate);
                jEndDateChooser.setDate(endDate);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thực hiện truy vấn. Vui lòng kiểm tra lại", "Message", JOptionPane.WARNING_MESSAGE);
                System.err.println(ex.getMessage());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Không thể convert dữ liệu", "Message", JOptionPane.WARNING_MESSAGE);
                System.err.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxSubject = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTeacher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxTeachingFrameTime = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtTeachingTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jStartDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jEndDateChooser = new com.toedter.calendar.JDateChooser();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Môn học");

        jLabel2.setText("Giáo viên");

        jLabel3.setText("Khung giờ học");

        cbxTeachingFrameTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng t2,t4,t6", "Chiều t2,t4,t6", "Sáng t3,t5,t7", "Chiều t3,t5,t7" }));

        jLabel4.setText("Số giờ dạy");

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setText("Save");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTeacher)
                            .addComponent(cbxTeachingFrameTime, 0, 212, Short.MAX_VALUE)
                            .addComponent(txtTeachingTime)
                            .addComponent(jStartDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEndDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxTeachingFrameTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTeachingTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ScheduleManagerForm scheduleManagerForm = new ScheduleManagerForm(c, account);
        scheduleManagerForm.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (validation()) {
            if (s != null) {
                try {
                    s.setSubject(Subject.getSubjectByName(cbxSubject.getSelectedItem().toString()));
                    s.setTeacher(txtTeacher.getText());
                    s.setTeachingFrameTime(cbxTeachingFrameTime.getSelectedItem().toString());
                    s.setTeachingTime(Integer.parseInt(txtTeachingTime.getText()));
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                    String startDate = sdf.format(jStartDateChooser.getDate());
                    String endDate = sdf.format(jEndDateChooser.getDate());
                    s.setStartDate(startDate);
                    s.setEndDate(endDate);
                    if (Schedule.update(s)) {
                        JOptionPane.showMessageDialog(null, "Update thành công","Message", JOptionPane.INFORMATION_MESSAGE);
                        ScheduleManagerForm scheduleManagerForm = new ScheduleManagerForm(c, account);
                        scheduleManagerForm.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Update thất bại", "Message", JOptionPane.WARNING_MESSAGE);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thực hiện truy vấn. Vui lòng kiểm tra lại", "Message", JOptionPane.WARNING_MESSAGE);
                System.err.println(ex.getMessage());
                }
            } else {
                s = new Schedule();
                try {
                    s.setClassNo(c);
                    s.setSubject(Subject.getSubjectByName(cbxSubject.getSelectedItem().toString()));
                    s.setTeacher(txtTeacher.getText());
                    s.setTeachingFrameTime(cbxTeachingFrameTime.getSelectedItem().toString());
                    s.setTeachingTime(Integer.parseInt(txtTeachingTime.getText()));
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                    String startDate = sdf.format(jStartDateChooser.getDate());
                    String endDate = sdf.format(jEndDateChooser.getDate());
                    s.setStartDate(startDate);
                    s.setEndDate(endDate);
                    s = Schedule.insert(s);
                    if(s != null){
                        JOptionPane.showMessageDialog(null, "Thêm lịch thành công", "Message", JOptionPane.INFORMATION_MESSAGE);
                        resetForm();
                        s = null;
                    } else{
                        JOptionPane.showMessageDialog(null, "Thêm lịch thất bại", "Message", JOptionPane.WARNING_MESSAGE);
                        s = null;
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thực hiện truy vấn. Vui lòng kiểm tra lại", "Message", JOptionPane.WARNING_MESSAGE);
                    System.err.println(ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScheduleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScheduleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbxSubject;
    private javax.swing.JComboBox<String> cbxTeachingFrameTime;
    private com.toedter.calendar.JDateChooser jEndDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser jStartDateChooser;
    private javax.swing.JTextField txtTeacher;
    private javax.swing.JTextField txtTeachingTime;
    // End of variables declaration//GEN-END:variables

    private void loadCombobox() throws SQLException {
        List<Subject> subjects = Subject.getAllSubject();
        cbxSubject.removeAllItems();
        for (Subject s : subjects) {
            if (s.getStatus() == 1) {
                cbxSubject.addItem(s.getSubjectName());
            }
        }
    }

    private void resetForm() {
        cbxSubject.setSelectedIndex(0);
        txtTeacher.setText("");
        cbxTeachingFrameTime.setSelectedIndex(0);
        txtTeachingTime.setText("0");
        jStartDateChooser.setDate(null);
        jEndDateChooser.setDate(null);
    }

    private boolean validation() {
        if (txtTeacher.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin", "", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtTeachingTime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin", "", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (jStartDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày bắt đầu", "", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (jEndDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ngày kết thúc", "", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        String teacher = txtTeacher.getText();
        String teachingTime = txtTeachingTime.getText();
        if (teacher.length() > 50) {
            JOptionPane.showMessageDialog(null, "Họ tên giáo viên không vượt quá 50 ký tự", "", JOptionPane.WARNING_MESSAGE);
            txtTeacher.setText("");
            return false;
        }
        if (!Pattern.matches("[0-9]{1,11}", teachingTime)) {
            JOptionPane.showMessageDialog(null, "Số giờ dạy phải nhập toàn chữ số", "", JOptionPane.WARNING_MESSAGE);
            txtTeacher.setText("");
            return false;
        }

        return true;
    }
}
