/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Layouts;

import Entity.Account;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setResizable(false);   
    }
    public MainForm(Account account){
        initComponents();
        switch(account.getRole()){
            case "hr":
                btnEmpManager.setEnabled(false);
                btnMarkManager.setEnabled(false);
                break;
            case "teacher":
                btnEmpManager.setEnabled(false);
                btnStudentManager.setEnabled(false);
                btnSubjectManager.setEnabled(false);
                btnClassManager.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        btnEmpManager = new javax.swing.JButton();
        btnStudentManager = new javax.swing.JButton();
        btnClassManager = new javax.swing.JButton();
        btnSubjectManager = new javax.swing.JButton();
        btnMarkManager = new javax.swing.JButton();
        btnAttendence = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Form");

        btnEmpManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEmpManager.setForeground(new java.awt.Color(51, 51, 255));
        btnEmpManager.setText("Quản lý nhân viên");
        btnEmpManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpManagerActionPerformed(evt);
            }
        });

        btnStudentManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStudentManager.setForeground(new java.awt.Color(51, 51, 255));
        btnStudentManager.setText("Quản lý sinh viên");
        btnStudentManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagerActionPerformed(evt);
            }
        });

        btnClassManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClassManager.setForeground(new java.awt.Color(51, 51, 255));
        btnClassManager.setText("Quản lý lớp");
        btnClassManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassManagerActionPerformed(evt);
            }
        });

        btnSubjectManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubjectManager.setForeground(new java.awt.Color(51, 51, 255));
        btnSubjectManager.setText("Quản lý môn học");
        btnSubjectManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectManagerActionPerformed(evt);
            }
        });

        btnMarkManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMarkManager.setForeground(new java.awt.Color(51, 51, 255));
        btnMarkManager.setText("Quản lý điểm");

        btnAttendence.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAttendence.setForeground(new java.awt.Color(51, 51, 255));
        btnAttendence.setText("Điểm danh");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMarkManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubjectManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClassManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudentManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAttendence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnEmpManager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnStudentManager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnClassManager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSubjectManager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMarkManager, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnAttendence, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("STUDENT MS");

        jMenu1.setText("Trang chủ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tài khoản");

        jMenuItem1.setText("Thông tin tài khoản");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(489, 489, 489))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpManagerActionPerformed
        // TODO add your handling code here:
        EmployeeManager employeeManager = new EmployeeManager();
        JInternalFrame newFrame = new JInternalFrame();
        newFrame.add(employeeManager, BorderLayout.NORTH);
        newFrame.setVisible(true);
        newFrame.setSize(1007,582);
        jDesktopPane.removeAll();
        jDesktopPane.add(newFrame);
        newFrame.moveToFront();
        
    }//GEN-LAST:event_btnEmpManagerActionPerformed

    private void btnClassManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassManagerActionPerformed
        // TODO add your handling code here:
        ClassManager classManager = new ClassManager();
        JInternalFrame newFrame = new  JInternalFrame();
        newFrame.add(classManager);
        newFrame.setVisible(true);
        newFrame.setSize(1007,582);
        jDesktopPane.removeAll();
        jDesktopPane.add(newFrame);
        
    }//GEN-LAST:event_btnClassManagerActionPerformed

    private void btnStudentManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagerActionPerformed
        // TODO add your handling code here:
        StudentManager studentManager = new StudentManager();
        JInternalFrame newFrame = new JInternalFrame();
        newFrame.add(studentManager);
        newFrame.setVisible(true);
        newFrame.setSize(1007, 582);
        jDesktopPane.removeAll();
        jDesktopPane.add(newFrame);
    }//GEN-LAST:event_btnStudentManagerActionPerformed

    private void btnSubjectManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectManagerActionPerformed
        // TODO add your handling code here:
        SubjectManager subjectManager = new SubjectManager();
        JInternalFrame newFrame = new JInternalFrame();
        newFrame.add(subjectManager);
        newFrame.setVisible(true);
        newFrame.setSize(1007, 582);
        jDesktopPane.removeAll();
        jDesktopPane.add(newFrame);
    }//GEN-LAST:event_btnSubjectManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    private void initilaze(){
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendence;
    private javax.swing.JButton btnClassManager;
    private javax.swing.JButton btnEmpManager;
    private javax.swing.JButton btnMarkManager;
    private javax.swing.JButton btnStudentManager;
    private javax.swing.JButton btnSubjectManager;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel leftPanel;
    // End of variables declaration//GEN-END:variables
}
